# Generated by Django 5.1.3 on 2025-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
