# Generated by Django 5.1.3 on 2025-04-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_drug_price_alter_drug_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
