# Generated by Django 5.2 on 2025-04-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_order_paid_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
